### ISSUE TITLE
Strange build errors

### ISSUE THREAD

**Issue by mtruyens** [binaryage/dirac#10]
Hi, 

Since upgrading to 0.2.0, I get very weird errors during execution (in fact, my web app refuses to load due to the severity of the errors). See attached screenshot. 

Initially the problem occurred on my main development machine, and after some fiddling (reinstall extension, delete and reinstall lein, clean build, renaming the resulting .JS file compiled by CLJS, etc.) suddenly everything worked again. 

Today I had exactly the same problem on my second development machine, and no matter what I try, I always get the same error. Merely including "[dirac.runtime :as dirac]" (not even calling dirac/install!) causes the error. Note that: 
- no errors are shown during compilation/building;
- devtools does not cause any problems; 
- the sample project works fine as well; 
- clicking on the links referenced in the error messages is not of any help (they all return empty files, probably because they are too low-level/internal?).

I am using the same Clojure and dirac/devtools versions as the sample project, and using Chrome 50...

Thanks in advance for your help!

<img width="656" alt="screen shot 2016-05-02 at 20 13 00" src="https://cloud.githubusercontent.com/assets/1895793/14963094/603c6e64-10a2-11e6-85f9-19ebf4e099d7.png">

**Comment by darwin** [comment]
From the errors I would guess that [prefs.cljs](https://github.com/binaryage/dirac/blob/master/src/runtime/dirac/runtime/prefs.cljs) compilation produced invalid javascript file. Second error then makes sense because prefs.js failed to load and create `dirac.runtime.prefs` namespace.

Please go into your target folder for your cljs build output (on disk) and open dirac/runtime/prefs.js from there. I would guess there will be some compilation warnings or errors emitted directly into javascript code. I had this issue when my macros did println or similar. Maybe my env reading code brought something silly in. We will see.

**Comment by mtruyens** [comment]
Thanks for the fast reply! 

Unfortunately, I don't immediately see any warnings in prefs.js (attached is the entire output of the dirac subfolder). 

On a side note: the prefs.js on the non-working development machine is identical (except for the auto-generated numbers) to the prefs.js of the working machine. 

[dirac.zip](https://github.com/binaryage/dirac/files/245768/dirac.zip)

**Comment by mtruyens** [comment]
...and on the previously main development machine, Dirac now refuses operation. Strange thing is, the message "Installing Dirac Runtime and enabling features :repl" contradicts the error message just below. (Both messages are shown after refresh of the page.)

Hope this helps to track down the weird behaviour that's going on...

<img width="754" alt="screen shot 2016-05-02 at 22 03 18" src="https://cloud.githubusercontent.com/assets/1895793/14966297/eb5a1f50-10b1-11e6-9cf9-df9bdb8b56ad.png">

**Comment by darwin** [comment]
Ok, the code looks fine. Also `dirac.runtime.prefs.static_prefs` is empty map. So my theory about invalid code gen due to some crazy envrion var is not the case.

**Comment by darwin** [comment]
One puzzling thing is why your source code links have VM***_name.js. In my projects the source code links mention real names like "core.cljs" or "util.cljs".

I think this has something to do with out problem at hand. Dirac Runtime is executed in some different javascript context than REPL code.

**Comment by darwin** [comment]
Could you show what is in that "http://localhost:3000" dropdown? Do you run any Extensions which provide content scripts? Any iframes in your page?

**Comment by darwin** [comment]
btw. that dropdown should have first item "top" which should be the main (and only) javascript context under standard circumstances.

**Comment by mtruyens** [comment]
Good hint: apparently the error about the runtime not being installed, was caused by the presence of the React Developer Tools (latest version - 0.14.9). Not a big issue for me to disable, but maybe good to indicate on the Readme pages, because the React Developer Tools are quite popular?

This solves the problem on my main development machine, but the initial SyntaxError on the secondary development machine remains, even while all extensions are disabled (I just tried with a fresh profile...)

<img width="1080" alt="screen shot 2016-05-02 at 22 19 28" src="https://cloud.githubusercontent.com/assets/1895793/14966762/61eb9016-10b4-11e6-97a5-62b400ad3095.png">

**Comment by mtruyens** [comment]
BTW, disabling the React Developer Tools does solve the weird filenames (on both development machines).

**Comment by darwin** [comment]
Now when you have real files working. Click on the file link in the devtools and you should see js source code which was actually loaded(cached) and then error-ed.

Do you see any difference from files you sent?

**Comment by mtruyens** [comment]
Correction on the previous comment: even when the React Developer Tools are completely uninstalled, the weird filenames error is apparently only resolved on the first load of the Dirac Window (see first screenshot). On the second load, one of the filenames becomes weird, and on the third load of the same page, all the filenames become weird...
<img width="787" alt="screen shot 2016-05-02 at 22 35 10" src="https://cloud.githubusercontent.com/assets/1895793/14967225/8dfafcda-10b6-11e6-98b3-b715250dd499.png">
<img width="856" alt="screen shot 2016-05-02 at 22 35 22" src="https://cloud.githubusercontent.com/assets/1895793/14967229/9053fa18-10b6-11e6-9bf2-b2105af3ae9a.png">
<img width="847" alt="screen shot 2016-05-02 at 22 37 58" src="https://cloud.githubusercontent.com/assets/1895793/14967232/92ef80e4-10b6-11e6-9134-677a24fa1643.png">

**Comment by darwin** [comment]
How do you load the Dirac Window? Right now you have Dirac opened "as panel" and reloading it means reloading your app's page. I tried it here and was unable to reproduce it. My files stay the same.

What happens when you change Dirac Extension Options to open Dirac Windows "as Window"?

**Comment by mtruyens** [comment]
Clicking on the normal filenames (e.g. core.js or util.js in the screenshots above) indeed shows the contents of the Javascript file. 

Clicking on the weird filenames shows an empty yellow pane...
<img width="767" alt="screen shot 2016-05-02 at 22 40 39" src="https://cloud.githubusercontent.com/assets/1895793/14967331/124e01f8-10b7-11e6-8b06-656ee76931d4.png">

**Comment by darwin** [comment]
Something fishy is going on because also your js-context dropdown changes between first and second load.

**Comment by mtruyens** [comment]
The problem with the weird file names is not solved by switching to a Window...
<img width="861" alt="screen shot 2016-05-02 at 22 44 09" src="https://cloud.githubusercontent.com/assets/1895793/14967382/669a52d4-10b7-11e6-847f-f77e8cfd23d7.png">

**Comment by darwin** [comment]
Can you try to run your Chrome with clean user profile? Don't install any extensions. Just Dirac Extension.

**Comment by darwin** [comment]
Also I assume internal DevTools don't exhibit the weird filenames when the page gets reloaded, right?

**Comment by mtruyens** [comment]
Correct the standard Chrome DevTools always show the correct filenames, even upon reload.

**Comment by mtruyens** [comment]
Sorry, not any difference after starting Chrome with a fresh new profile and only installing Dirac (and not changing any setting). Filenames OK upon first load, becoming weird after reloads...

**Comment by darwin** [comment]
Maybe we exposed some incompatibility between external DevTools and your Chrome version. There is no way how Dirac patches could interfere with resolution of filenames. 

Btw. do you use current Chrome Canary build?

**Comment by mtruyens** [comment]
I use the regular Chrome (version 50), but I'll try immediately with the Canary.

**Comment by darwin** [comment]
That could be an issue. Technically you are now using "DevTools from future" with your Chrome version. DevTools and Chrome are developed in a lockstep and divergence of those two components could cause problems.

https://github.com/binaryage/dirac/blob/master/docs/faq.md#why-should-i-use-recent-chrome-canary-with-dirac-devtools

**Comment by mtruyens** [comment]
You were right: switching to Canary solves the problem of the weird filenames (even after reload). 
Sorry, I should have read your FAQ about that one, I wrongly assumed that having a recent version of Chrome (> 47) would have been OK. 

Do you think the Syntax Error on my secondary development machine will be resolved with a new build of Dirac?

**Comment by darwin** [comment]
Official stable Chrome is several months behind current Chrome Canary. And DevTools development has been [quite active](https://github.com/binaryage/dirac/tree/devtools) (and they were changing some internals). It is too long time for Dirac to stay compatible with stable Chrome. Unfortunately.

I will probably add some warnings about "too old" Chrome versions.

**Comment by darwin** [comment]
Not sure about your syntax errors, but now you should finally be able to inspect the sources in DevTools and see the true state.

**Comment by mtruyens** [comment]
Indeed, syntax errors are also resolved by the Canary version. (Very strange, I would never have expected this.)
Many, many thanks for your time -- and for your wonderful tool. It is a true productivity enhancement!

**Comment by darwin** [comment]
You are welcome. I'm glad you have resolved it. 

What do you use as code editor / IDE. Next big feature will be "joining Dirac REPL session from other nREPL sessions". So for example in Cursive, you can join Dirac REPL and code sent from Cursive code editor will show up as it would be entered in Dirac REPL in the DevTools (including history, etc)

**Comment by mtruyens** [comment]
I use Cursive, so that would be enormously cool!

Maarten
