### ISSUE TITLE
No such var: string/index-of

### ISSUE THREAD

**Issue by Slotkenov** [binaryage/dirac#16]
When I update the `binaryage/dirac` dependency in my `build.boot` file from version `0.2.0` to `0.3.0`, and then I run `boot` from the command line, I get the following error message:
```
clojure.lang.ExceptionInfo: No such var: string/index-of
    data: {:file "dirac/nrepl/sessions.clj", :line 149}
java.lang.RuntimeException: No such var: string/index-of
```
See: https://github.com/binaryage/dirac/blob/v0.3.0/src/nrepl/dirac/nrepl/sessions.clj#L149

**Comment by darwin** [comment]
You are using Clojure 1.7, but Clojure 1.8 is required in 0.3.0. This will be fixed in the next release.

Duplicit #15

**Comment by darwin** [comment]
A temporary fix for you could be to clone this repo and run `lein install` to install current bleeding edge version into your local maven repo. The fix is already in master: https://github.com/binaryage/dirac/commit/da2bc1e8cd265b31cfcaa2676898f8a3256152e0

**Comment by Slotkenov** [comment]
You're right. I had in my boot properties still version 1.7 for Clojure. Missed that one. Now it works!
