### ISSUE TITLE
Wrong completion after a require with alias

### ISSUE THREAD

**Issue by arichiardi** [binaryage/dirac#21]
It is very good to be able to inspect vars with dirac.

I know it is alpha/early stage, I just want to report one thing.

![selection_008](https://cloud.githubusercontent.com/assets/1724788/15638228/abe058d6-25d2-11e6-835a-8b752d56e38a.png)

If I require a namespace with an alias, then auto-completion shows symbols starting with the alias but no the namespace symbols (we have had the same problem on clojurescript.io btw).

**Comment by darwin** [comment]
Good point. I'd like to support aliases at some point. But for this I need a reliable library to parse `ns` forms, which would give me back information about aliases. I haven't found any library to do that yet.

Currently I have to parse ns name at least, and I use Sierra's `clojure.tools.namespace.parse` library for that: https://github.com/binaryage/dirac/blob/master/src/implant/dirac/implant.cljs#L64
