### ISSUE TITLE
Feature request: time travel debugger like Redux DevTools

### ISSUE THREAD

**Issue by comerc** [binaryage/dirac#29]
https://github.com/gaearon/redux-devtools
https://github.com/cyclejs/cycle-time-travel
https://github.com/vuejs/vue-devtools
http://debug.elm-lang.org/

**Comment by danielcompton** [comment]
I don't know if this is really a `dirac` feature? It *might* be a cljs-devtools feature, but probably it needs to be specific to the UI framework you're using? For example, notice how each of the time travel tools you reference are for a specific framework, not all of JavaScript.

**Comment by darwin** [comment]
I wanted to write the same as @danielcompton. I don't see a way how to implement such feature without it being framework-specific. It boils down to the requirement that user needs to write time-travel-aware code (or use a specific library which somehow allows that). This is not even a feature for cljs-devtools IMO.

**Comment by comerc** [comment]
I see two cases: Om.Next and Reagent+Re-Frame.

**Comment by darwin** [comment]
I'm definitely not going to implement this personally. But I'm open for someone to step in and implement it.

But I'm still not convinced that much of this can be implemented by Dirac itself. I believe majority of work has to be implemented on framework side. For example in case of re-frame, it would have to expose some way how to record app-db history and walk it. And user code has to be aware of such possibility (e.g. no side-effects in handlers). If you wanted to control this via Dirac, then Dirac would need to use some kind of time-traveling API exposed by re-frame and present it somehow in the UI. And then why would you need Dirac in the first place. You could build in-app UI to support time-traveling debugging in the app itself (and use Dirac as a dumb debugger).

@comerc  But maybe I'm missing something. Do you have any a specific idea how this should be implemented?
