### ISSUE TITLE
Error encountered performing task 'do' in profiles

### ISSUE THREAD

**Issue by abhi18av** [binaryage/dirac#35]
I've followed the instructions at the [Dirac sample](https://github.com/binaryage/dirac-sample) and [Dirac installation](https://github.com/binaryage/dirac/blob/master/docs/installation.md) 

but it throws the following error

`starting HTTP server on port 9977 => http://localhost:9977
Error encountered performing task 'do' with profile(s): 'base,system,user,provided,dev,demo'
Suppressed exit`

Please guide me a bit, this is a great tool!
Thanks

**Comment by darwin** [comment]
What is your `lein -version`?

My is:
```
> lein --version                                                                                                                                                                                                                                                                        Leiningen 2.7.0 on Java 1.8.0_60 Java HotSpot(TM) 64-Bit Server VM
```

**Comment by abhi18av** [comment]
Mine is 

`Leiningen 2.6.1 on Java 1.8.0_91 Java HotSpot(TM) 64-Bit Server VM`

**Comment by darwin** [comment]
That is correct. Do you have python on your machine?

Try to run `./scripts/dev-server.sh` directly from command-line.
