### ISSUE TITLE
add hooks to console.log API to allow 2-way communication between page and dev tools

### ISSUE THREAD

**Issue by meta-meta** [binaryage/dirac#38]
relevant conversation here:
https://clojurians.slack.com/archives/clojurescript/p1473893842002423

End goal is to send messages from a reagent webapp to figwheel and back. Specifically, some terminal will be rendered as a texture in an A-frame VR scene. 

eval and print at least. intellisense would be a huge bonus.

re: loading dev tools in iframe, this won't work with A-frame unfortunately: https://github.com/aframevr/aframe/issues/399

**Comment by darwin** [comment]
I have added `request-eval-cljs` and `request-eval-js` into `dirac.runtime.repl` namespace[1].

This will be available in the next release 0.6.7.

To capture complete output. You will have to hijack methods on console object. For inspiration you can look here[2] (I capture console output for automated testing).

[1] https://github.com/binaryage/dirac/blob/37ec8ba6fa934fb36be910f63794dcf76a2d3c4d/src/runtime/dirac/runtime/repl.cljs#L164-L170
[2] https://github.com/binaryage/dirac/blob/37ec8ba6fa934fb36be910f63794dcf76a2d3c4d/src/automation/dirac/automation/scenario.cljs#L68-L101
