### ISSUE TITLE
Dirac disconnects when inspecting DOM elements.

### ISSUE THREAD

**Issue by njj** [binaryage/dirac#40]
Hi all, first off awesome work on this tool.  I'm having a bit of an issue where the Dirac tool will disconnect if I inspect an element in the browser, it appears that the issue is from another dev tools being opened up in Chrome.  Is there any resolution to this issue.

(Sorry if this is a duplicate, I looked in the closed issues from something similar).

**Comment by darwin** [comment]
You must not open internal or any other "debugging protocol client" during Dirac session. 

Why don't you use Dirac for DOM inspection (click on the inspection icon in Dirac if keyboard shortcuts trigger internal devtools)?

This is a fundamental limitation inside Chrome. They allow only one debugging protocol client:
https://developer.chrome.com/devtools/docs/debugger-protocol#simultaneous
https://bugs.chromium.org/p/chromium/issues/detail?id=129539

There was an effort to multiplex debugger connection[1], but don't think you want to get that far:
https://github.com/sidorares/crmux

**Comment by njj** [comment]
@darwin Thanks!
