### ISSUE TITLE
in-ns issues

### ISSUE THREAD

**Issue by FongHou** [binaryage/dirac#47]
Hi,

I noticed in-ns doesn't seem to be working anymore. It used to be working, but I can't remember when I used it last time.

I did a git clone dirac-sample project to reproduce it. Here is the screenshot.

- require, then in-ns to dirac-sample.demo. but hello! gave 'call' of undermined.
- eval a simple expression, ns switched back cljs.user in the prompt. 

<img width="963" alt="screen shot 2016-10-24 at 5 09 34 pm" src="https://cloud.githubusercontent.com/assets/13973254/19664454/6554b000-9a0e-11e6-9466-55b2914ff855.png">

**Comment by darwin** [comment]
This is quite possible. There may be some deeper consequences of
https://github.com/clojure/clojurescript/commit/c9c1229b5415b5176f8520e9ca2ba0879158d188
(via 
0a73443902babd5ef3b73c12e28ea489f564835f)

**Comment by darwin** [comment]
Found the problem. This is a bug introduced by me in 0.7.0 nREPL rewrite. Sorry for that.

Will fix it over the weekend.

A workaround: use fully qualified namespace names.

**Comment by FongHou** [comment]
Sounds good! 

dirac is such a great tool. I can't imagine how to debug clojurescript program without it.
