### ISSUE TITLE
"require" broken?

### ISSUE THREAD

**Issue by p-himik** [binaryage/dirac#49]
Somewhere around version 0.7.5 executing
```clojure
> (require '[re-frame.db :refer [app-db]])
> @app-db
```
in the browser console would give a nice representation of app-db current value.
Now none of such statements are working - in this case `app-db` is `undefined`.
At the same time, `require`ing works inside `lein repl` (although it doesn't have the same value as app-db in browser).

**Comment by darwin** [comment]
Just did a quick test and it works for me with 0.8.0:
https://dl.dropboxusercontent.com/u/559047/dirac-reframe-issue-49.png

I modified [dirac-sample](https://github.com/binaryage/dirac-sample) project and added [re-frame "0.8.0"] as a new dependency.

While doing it I had to add a hard require to re-frame.db to demo.cljs. ClojureScript 1.9.293 has a new way of doing standalone `require` and it somewhat broken if the required namespace wasn't required in any of the existing sources. Maybe you ran into this issue? 

See https://github.com/bhauman/lein-figwheel/issues/490.

**Comment by p-himik** [comment]
I had ClojureScript 1.9.229 - with this version a hard require didn't change anything.
After I bumped the version to 1.9.293, the requirement from Dirac console now works without any hard require at all.
Some strange inconsistency, but I guess this won't be an issue if I pay attention to ClojureScript updates.

Thanks for the help!
