### ISSUE TITLE
Chrome extension doesn't work

### ISSUE THREAD

**Issue by zarkone** [binaryage/dirac#50]
Hello!

I've installed extension from webstore to my chrome`Version 54.0.2840.71 (64-bit) macOS Sierra 10.12.1` and see this error on my cljs project page, constantly repeating: 

` Uncaught SyntaxError: Invalid or unexpected token                   VM3986:1`

Also, extension has `!` red badge.

**Comment by darwin** [comment]
https://github.com/binaryage/dirac/blob/master/docs/faq.md#why-should-i-use-recent-chrome-canary-with-dirac-devtools
