### ISSUE TITLE
"Use of undeclared var" & "no such namespace" errors

### ISSUE THREAD

**Issue by mtruyens** [binaryage/dirac#6]
When I try to execute CLJS-code from the Dirac REPL, I always get "use of undeclared var" errors (even though the function call usually executes correctly) and "no such namespace" errors (for imported namespaces in the current namespace). I did execute an (in-ns ...) call first to go to the correct namespace.

**Comment by darwin** [comment]
Did you call `(require 'your.ns)` first?

**Comment by mtruyens** [comment]
Thanks. You are right -- in hindsight, this should have been obvious. 

Perhaps a good idea to mention it in the documentation? (The current screenshots only show "(in-ns 'my.ns)", which suggested to me that this was enough.)

**Comment by darwin** [comment]
"Hello, World!" demo in dirac-sample project walks people through requiring a file in the REPL:
https://github.com/binaryage/dirac-sample#hello-world
