### ISSUE TITLE
Canary 60.0.3076.0/Mac is broken

### ISSUE THREAD

**Issue by darwin** [binaryage/dirac#60]
https://github.com/binaryage/dirac-sample/issues/3

**Comment by darwin** [comment]
Canary 60.0.3077.0/Mac works again.

**Comment by darwin** [comment]
Canary 60.0.3078.0 must switch to [Dirac 1.2.5](https://github.com/binaryage/dirac/releases/tag/v1.2.5).

**Comment by darwin** [comment]
Chromium 60.0.3079.0 is broken again with Dirac 1.2.5 due to [this revert](https://chromium.googlesource.com/chromium/src/+/c1bc835e0ead2a64955b96ebde29ea191280f99e) again.

**Comment by pepe** [comment]
Hi, it seems in Chromium 60.0.3080.0, everything is working even with Use backend-supported API/CSS. 

Great work!

**Comment by darwin** [comment]
Yes, 1.2.5 should work again with 60.0.3080, the patch landed again here:
https://chromium.googlesource.com/chromium/src/+/3b36efad6b17e10ae243a8668528aae310a312da

Let's hope it won't get reverted again.

**Comment by pepe** [comment]
Great.

**Comment by darwin** [comment]
Looks like the patch finally landed without auto-reverts.
