### ISSUE TITLE
Doc for user namespace throws an error

### ISSUE THREAD

**Issue by arichiardi** [binaryage/dirac#68]
Hello @darwin, reporting duty.

I have a namespace called `rest-resources-viz.model` in my project and a function with docstring (don't know if it matters, just pulling the info out).

When I do:

```
(in-ns 'rest-resources-viz.model)
(doc highlighted-nodes)
```

this happens:

```
TypeError: Cannot read property 'call' of undefined
    at rest_resources_viz$model$repl_job_51 (repl-job-000051.cljs:1)
    at dirac$runtime$repl$capture_output (repl.cljs:172)
    at dirac$runtime$repl$present (repl.cljs:186)
    at dirac$runtime$repl$execute_job (repl.cljs:195)
    at dirac$runtime$repl$eval_captured (repl.cljs:203)
    at Object.dirac$runtime$repl$eval [as eval] (repl.cljs:262)
    at repl-job-000051.js:1
hints.cljs:61 XMLHttpRequest cannot load repl://dirac-repl/dirac/9f63557a-1/repl-job-000051.js. Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https.
```

I tried also `clojure.repl/doc`, no error but no docstring as well:

```
(clojure.repl/doc highlighted-nodes)

null
```

**Comment by darwin** [comment]
`(cljs.user/doc highlighted-nodes)` should work.

I believe this is standard REPL behaviour, it requires doc into `cljs.user` namespace only.

This is the init code which runs to bootstrap REPL:

https://github.com/binaryage/dirac/blob/248eb89548e8b0790bfd3440ed6940479bdcd7e5/src/nrepl/dirac/nrepl/config_helpers.clj#L8-L12

So also `(cljs.repl/doc highlighted-nodes)` should work.

**Comment by darwin** [comment]
Ok, I don't think this is in the scope of Dirac. I think something like "global" `doc` (or REPL-special command) should be implemented in CLJS REPL so that it works consistently across all REPLs.
