### ISSUE TITLE
"Store as global variable" does not work

### ISSUE THREAD

**Issue by p-himik** [binaryage/dirac#71]
If you invoke a context menu on any CLJS object in the console, you can see two items - "Show as JavaScript object" (works, although there's no way back to the CLJS representation) and "Store as global variable". Clicking on the latter results in something that looks like this:
![image](https://user-images.githubusercontent.com/4410314/33444413-d2c262da-d62c-11e7-9204-5c71d9f2e971.png)
As you can see, `temp3` is undefined.
What's interesting, is that `temp3` is actually resolvable within JS console.

**Comment by darwin** [comment]
I have just tested it with latest Dirac under macOS and the feature works properly.

You are simply missing the fact that "a global variable" means "a javascript global variable" and you are inside ClojureScript console prompt. That means that you have to refer to it via `js/` pseudo namespace. In your example `js/temp3`. Unqualified names are scoped to current ClojureScript REPL namespace. See `in-ns` REPL special function.

We could probably introduce a new context-menu option which would define local variable in current ClojureScript namespace. But I don't think it is worth the effort.

**Comment by p-himik** [comment]
Yeah, I admit that was dumb of me, especially since I noticed the availability in the JS console myself. Thanks for the explanation!
