### ISSUE TITLE
Setting :agent-host does not seem to work

### ISSUE THREAD

**Issue by kidpollo** [binaryage/dirac#77]
I am running my repl in a different host than localhost in a VM in my computer. The dirac agent is definitely running on my repl but on chrome I get this error `
Dirac Agent is not listening at ws://localhost:8231 (need help?).`  It should be trying to connect to the agent on other host. Any ideas if I am missing something? I am setting up via preloads and setting host and port as the docs say.

**Comment by kidpollo** [comment]
Let me describe what I want to do. I am setting up a brand new app with Clojure CLI tools. The way I do dev in my computer is I run a VM with archlinux where I run and edit code through the terminal or a remote x session. That is why when I run my browser I hit the VM IP and it seems to work fine with figwheel when I set the `:websocket-host :server-hostname` in the config.

Then I tried to setup dirac and this is roughly what I ended up with:

This is the command  and output I am attempting to run my figwheel build with

```
 env DIRAC_NREPL/WEASEL_REPL/HOST="192.168.3.2" clj -R:repl build.clj figwheel 8230                                                  <master♺ >

Figwheel: Starting server at http://0.0.0.0:3449
Figwheel: Watching build - dev
Compiling build :dev to "src/public/js/compiled/app.js" from ["src"]...
Successfully compiled build :dev to "src/public/js/compiled/app.js" in 1.164 seconds.
Figwheel: Starting nREPL server on port: 8230

Dirac Agent v1.2.33
Connected to nREPL server at nrepl://localhost:8230.
Agent is accepting connections at ws://localhost:8231.
```

This is an extract of build.clj
```clojure
(def compiler-config {:main 'my-app.core
                      :output-to "src/public/js/compiled/app.js"
                      :output-dir "src/public/js/compiled/out"
                      :asset-path "js/compiled/out"
                      :source-map-timestamp true
                      :preloads '[devtools.preload dirac.runtime.preload]
                      :external-config {:devtools/config {:features-to-install :all}
                                        :dirac.runtime/config {:agent-host "192.168.3.2"
                                                               :agent-port 8231}}

                      })

(defmethod task "figwheel" [[_ port]]
  (with-namespaces [figwheel-sidecar.repl-api dirac.agent]
    (figwheel-sidecar.repl-api/start-figwheel!
     {:figwheel-options (cond-> {}
                          port (merge {:nrepl-port (some-> port Long/parseLong)
                                       :nrepl-middleware [
                                                          ;"cider.nrepl/cider-middleware"
                                                          ;"refactor-nrepl.middleware/wrap-refactor"
                                                          ;"cemerick.piggieback/wrap-cljs-repl"
                                                          "dirac.nrepl/middleware"]}))
      :all-builds       [{:id "dev"
                          :figwheel {:on-jsload "bursacon.core/mount-root"
                                     :websocket-host :server-hostname}
                          :source-paths [source-dir]
                          :compiler dev-config}]})
    (dirac.agent/boot!)
    (when-not port
      (figwheel-sidecar.repl-api/cljs-repl))))

```

**Comment by kidpollo** [comment]
![dirac v1 2 33 _-_ ui _ http___192 168 3 2_3449_ _ chrome_68 0 3398 0 _ windows_10 0 2018-04-23 21 52 09](https://user-images.githubusercontent.com/8182/39167058-e6aab06e-4741-11e8-8699-8256991c8f2a.png)
This is the output I see on the dirac console

**Comment by kidpollo** [comment]
localhost is not where the agent is running. The agent is running on 192.168.3.2

**Comment by darwin** [comment]
Wait, now I realized that you run your browser outside of the VM, not inside as I thought.

Is this your setup?

## Host machine
1. nREPL server
2. Dirac Agent
3. Browser

## VM
1. cljs compiler serving compiled files via figwheel

Then I think all should stay as defaults. Because Dirac Browser Extension connects to Dirac Agent on localhost (on host machine). And weasel inside Dirac Browser Extension also connects to Dirac Agent on localhost (on host machine).

**Comment by darwin** [comment]
Maybe you could share your skeleton project? I would take a look.

**Comment by darwin** [comment]
Ah, I'm a bit slower, now I think you are running it this way:

# Host Machine
1. Browser

# VM
1. nREPL server
2. Dirac Agent
3. cljs compiler serving compiled files via figwheel

Then you need to:
1. set `:dirac.runtime/config :agent-host` to VM's IP as seen from your host machine
2. set `DIRAC_NREPL/WEASEL_REPL/HOST` to Host machine's IP as seen from your VM
