### ISSUE TITLE
dirac dependency must be specified in :dev profile

### ISSUE THREAD

**Issue by tvaughan** [binaryage/dirac#8]
I'd like to be able to do:

```clojure
  :profiles {:dirac
             {:dependencies [[binaryage/dirac "0.1.3"]]
              :repl-options {:nrepl-middleware [dirac.nrepl.middleware/dirac-repl]
                             :port 8231
                             :init (do
                                     (require 'dirac.agent)
                                     (dirac.agent/boot!))}}
```

But this doesn't work. When I run `lein with-profile +dirac repl` the error is:

```
> java.lang.IllegalArgumentException: No matching ctor found for class clj_logging_config.log4j.proxy$org.apache.log4j.WriterAppender$ff19274a, compiling:(clj_logging_config/log4j.clj:37:18)

Dirac failed to require its implementation. This is likely caused by missing or wrong dependencies in your project.
Please review your project configuration with Dirac installation instructuctions here: https://github.com/binaryage/dirac#installation.
 #error {
 :cause No matching ctor found for class clj_logging_config.log4j.proxy$org.apache.log4j.WriterAppender$ff19274a
 :via
 [{:type clojure.lang.Compiler$CompilerException
   :message java.lang.IllegalArgumentException: No matching ctor found for class clj_logging_config.log4j.proxy$org.apache.log4j.WriterAppender$ff19274a, compiling:(clj_logging_config/log4j.clj:37:18)
   :at [clojure.lang.Compiler analyzeSeq Compiler.java 6875]}
  {:type java.lang.IllegalArgumentException
   :message No matching ctor found for class clj_logging_config.log4j.proxy$org.apache.log4j.WriterAppender$ff19274a
   :at [clojure.lang.Compiler$NewExpr <init> Compiler.java 2548]}]
 :trace
 [[clojure.lang.Compiler$NewExpr <init> Compiler.java 2548]
```

This does work:

```clojure
  :profiles {:dev
             {:dependencies [[binaryage/dirac "0.1.3"]]}
             :dirac
             {:repl-options {:nrepl-middleware [dirac.nrepl.middleware/dirac-repl]
                             :port 8231
                             :init (do
                                     (require 'dirac.agent)
                                     (dirac.agent/boot!))}}
```

**Comment by darwin** [comment]
Ah, it looks like `lein repl` does use a different set of dependencies than the dependencies of your project (and what you specify on command-line with-profile).

After reading this:
https://github.com/technomancy/leiningen/blob/master/doc/PROFILES.md#default-profiles
and this
https://github.com/technomancy/leiningen/blob/master/doc/PROFILES.md#replacing-default-repl-dependencies

Your `:dev` solution works. Because :dev is used in default profile which is used by repl process. You could also try to use `:repl` instead of `:dev`. That would be narrower deps specification I believe.

Leaving open for readme/docs update.

**Comment by darwin** [comment]
Also I'm glad to see that Dirac caught bad dependencies setup. Tracing source of such error without "Dirac failed to require its implementation." hint would be pretty frustrating.

**Comment by ProjectFrank** [comment]
That configuration seems to work fine here:

https://github.com/circleci/frontend/blob/master/project.clj#L121

**Comment by darwin** [comment]
In new docs, I have recommended to put Dirac repl-related config under `:repl` profile.

https://github.com/binaryage/dirac/blob/master/docs/install.md#start-nrepl-server

This should work for most people.
