### ISSUE TITLE
Run Dirac CLI in the background

### ISSUE THREAD

**Issue by binarykitchen** [binaryage/dirac#93]
Would be good if the `dirac` command would open Canary in the background and then just exists.

Like that I don't have to keep the terminal open. Thanks.

**Comment by darwin** [comment]
You can launch the tool without launching Chrome at the end and launch it separately by hand, try
`dirac launch --dry-chromium`

But this won't help you to remove the need for a terminal session. The script launches nREPL server, Dirac Agent and maybe other tools which need to run. And these tools could spit some output/errors so it is recommended to have their output somewhere in a Terminal session.

You can try to run dirac command in background via 
`dirac &`

But that does not help you in closing the terminal window neither. It just helps you to do something else there and later bring the background process back to foreground.

Personally I would recommend you to look into `tmux` or something similar. You can then do:
`tmux new-session dirac`

This will allow you to detach from the tmux terminal session (CTRL+B, D) and maybe attach to it later e.g. via `tmux attach`.

**Comment by binarykitchen** [comment]
Thanks, this helps
